[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyElevenlabs"
version = "0.0.3"
authors = [
  { name="Philip Lawall", email="philip@lawall.me" }
]
description = "Python wrapper for the ElevenLabs API"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/philiplawall/pyElevenLabs"
"Bug Tracker" = "https://github.com/philiplawall/pyElevenLabs/issues"
